name: Lint

on: [push]

jobs:
  Rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Set up Rubocop
        run: gem install rubocop rubocop-rspec
      - name: Run Rubocop checks
        run: rubocop .

  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Setup up Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Set up Prettier for Ruby
        run: gem install prettier
      - name: Run Prettier for Ruby checks
        run: rbprettier -c '**/*.rb'
